title=[${playlist-pos-1}/${playlist-count}] ${media-title} - mpv

screenshot-directory=~/

geometry=1280x720

volume=100
volume-max=250

osd-font=Cantarell
osd-font-size=22
osd-level=1
osd-on-seek=msg
osd-duration=1000
# osd-align-x=center
# osd-align-y=center

auto-window-resize=no
loop-playlist=no
force-window=yes
keepaspect-window=no
quiet=yes

# https://github.com/mpv-player/mpv/issues/4241
ytdl-format=bestvideo[height<=?360][fps<=?30][vcodec!=?vp9]+bestaudio/best
